DROP TABLE IF EXISTS hdb_peak;
CREATE TABLE hdb_peak(
     PEAKID     CHAR(4)     NOT NULL PRIMARY KEY
    ,PKNAME     VARCHAR(70)
    ,PKNAME2    VARCHAR(70)
    ,"LOCATION" VARCHAR(70)
    ,HEIGHTM    INTEGER
    ,HEIGHTF    INTEGER
    ,HIMAL      INTEGER
    ,REGION     INTEGER
    ,"OPEN"     BOOLEAN
    ,UNLISTED   BOOLEAN
    ,TREKKING   BOOLEAN
    ,TREKYEAR   CHAR(4)
    ,RESTRICT   VARCHAR(70)
    ,PHOST      INTEGER
    ,PSTATUS    INTEGER
    ,PEAKMEMO   TEXT
    ,PYEAR      CHAR(4)
    ,PSEASON    INTEGER
    ,PEXPID     VARCHAR(9)
    ,PSMTDATE   VARCHAR(6)
    ,PCOUNTRY   VARCHAR(70)
    ,PSUMMITERS VARCHAR(210)
    ,PSMTNOTE   VARCHAR(140)
    ,REFERMEMO  TEXT
    ,PHOTOMEMO  TEXT
) WITHOUT ROWID;